# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [17]:
import numpy as np
arr = np.linspace(0, 20, 28).reshape(4, 7)
arr -= np.amin(arr)
arr /= np.amax(arr)
arr

array([[0.        , 0.03703704, 0.07407407, 0.11111111, 0.14814815,
        0.18518519, 0.22222222],
       [0.25925926, 0.2962963 , 0.33333333, 0.37037037, 0.40740741,
        0.44444444, 0.48148148],
       [0.51851852, 0.55555556, 0.59259259, 0.62962963, 0.66666667,
        0.7037037 , 0.74074074],
       [0.77777778, 0.81481481, 0.85185185, 0.88888889, 0.92592593,
        0.96296296, 1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [18]:
arr = np.random.randint(0, 11, (8, 10))
print(arr)
ind = arr.sum(axis=1).argmin()
ind

[[ 3  1  7  1  7  5 10  2  1  3]
 [10  6  1  0  0  2  8 10  8  0]
 [ 6  5 10  6  2  5  3  5  1  9]
 [10  2  9  6  0  9  7  9  0  9]
 [ 6  6  1 10  4  1  5  4 10  0]
 [ 0  2  9  8  9  4  2  0  4  9]
 [ 2  6  3 10  4  9  8  3  7  3]
 [ 5  6  2 10  4  4  8  9  5  5]]


0

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [28]:
arr1 = np.random.randint(0, 11, size=3)
arr2 = np.random.randint(0, 11, size=3)
print(arr1, arr2)
print(np.sum((arr1 ** 2 - arr2 ** 2) ** 0.5))

[2 5 9] [5 0 2]
nan


C:\Users\kenni\AppData\Local\Temp\ipykernel_24836\1160386197.py:4: RuntimeWarning: invalid value encountered in power
  print(np.sum((arr1 ** 2 - arr2 ** 2) ** 0.5))


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [68]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
c *= -1
a = np.linalg.inv(a)
b = np.linalg.inv(b)
x = a @ c @ b
print(x)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Дополнительно

1. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [12]:
arr = np.array([range(i, i + 7) for i in range(1, 102, 10)])
arr

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2. Создать массив из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в массиве. Опредлить индекс этого значения.

In [11]:
arr = np.random.randint(0, 101, 20)
mx2 = np.max(arr[arr != np.max(arr)])
ind = np.where(arr == mx2)
print(mx2, ind)

86 (array([3], dtype=int64),)


3. Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [16]:
arr1 = np.random.randint(0, 11, size=(30, 3))
arr2 = np.random.randint(0, 11, size=(30, 3))
new = arr1[arr1 > arr2]
sm = np.sum(new)
print(new, sm, sep="\n")

[ 7  4  8 10 10  8 10  7  2  7  5 10  7 10  8  6 10  5 10  6 10  9  2  5
  8 10  9  7  3 10  7  4  5 10  8  7  9  6  9  6  6  2  3  7  7  5]
324


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [69]:
arr = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", delimiter=",", skiprows=1)
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [70]:
print(f"Min {np.amin(arr, axis=0)[1:]}\nMax {np.max(arr, axis=0)[1:]}\nMed {np.median(arr, axis=0)[1:]}")

Min [0 1]
Max [2147483647         39]
Med [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [71]:
q = np.quantile(arr, 0.75, axis=0)
arr[arr[:, 1] > q[1]] = q[1]

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [72]:
print(np.sum(arr[:, 1] == 0))
arr[arr[:, 1] == 0] = 1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [73]:
print(len(np.unique(arr[:, 0])))

74984


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [74]:
print(np.unique(arr[:, 2]), len(np.unique(arr[:, 2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 33 34 65] 33


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [75]:
print(arr[arr[:, 2] <= 5, :])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [76]:
ing_m = np.array(np.divide(arr[:, 2], arr[:, 1]))
print(ing_m, np.max(ing_m))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        1.        ] 23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [77]:
sor = arr[arr[:, 1].argsort()][::-1]
print(np.mean(sor[:100, 2]))

61.12


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [78]:
idx = np.random.randint(100000, size=10)
print(arr[idx, :])

[[    65     65     65]
 [    65     65     65]
 [106289     64      5]
 [ 69986     55     11]
 [437549     25      9]
 [218817     45      5]
 [    65     65     65]
 [154393     45     10]
 [466376     60      8]
 [265562     40     12]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [79]:
sr = np.mean(arr[:, 2])
print(f"{len(arr[arr[:, 2] < sr]) / len(arr) * 100}%")

75.345%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [80]:
new = arr.copy()
new = np.append(new, np.logical_and(new[:, 1] <= 20, new[:, 2] <= 5).astype(int)[:, None], axis=1)
print(new)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [    65     65     65      0]]


13. Выведите процент "простых" рецептов в датасете

In [81]:
print(f"{np.sum(new[:, -1]) / 1000}%")

9.943%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [82]:
sm = arr[arr[:, 1] < 10]
st = arr[np.logical_and(10 <= arr[:, 1], arr[:, 1] < 20)]
bi = arr[20 <= arr[:, 1]]
mn_shape = min(sm.shape[0], st.shape[0], bi.shape[0])
sm = sm[:mn_shape, :]
st = st[:mn_shape, :]
bi = bi[:mn_shape, :]
res_arr = np.array([sm, st, bi])
print(res_arr)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [     1      1      1]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
