# Numpy

–ú–∞—Ç–µ—Ä–∏–∞–ª—ã:
* –ú–∞–∫—Ä—É—à–∏–Ω –°.–í. "–õ–µ–∫—Ü–∏—è 1: –ë–∏–±–ª–∏–æ—Ç–µ–∫–∞ Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## –ó–∞–¥–∞—á–∏ –¥–ª—è —Å–æ–≤–º–µ—Å—Ç–Ω–æ–≥–æ —Ä–∞–∑–±–æ—Ä–∞

1. –°–≥–µ–Ω–µ—Ä–∏—Ä–æ–≤–∞—Ç—å –¥–≤—É—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤ `arr` —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏ (4, 7), —Å–æ—Å—Ç–æ—è—â–∏–π –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö –¥–µ–π—Å—Ç–≤–∏—Ç–µ–ª—å–Ω—ã—Ö —á–∏—Å–µ–ª, —Ä–∞–≤–Ω–æ–º–µ—Ä–Ω–æ —Ä–∞—Å–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω—ã—Ö –≤ –¥–∏–∞–ø–∞–∑–æ–Ω–µ –æ—Ç 0 –¥–æ 20. –ù–æ—Ä–º–∞–ª–∏–∑–æ–≤–∞—Ç—å –∑–Ω–∞—á–µ–Ω–∏—è –º–∞—Å—Å–∏–≤–∞ —Å –ø–æ–º–æ—â—å—é –ø—Ä–µ–æ–±—Ä–∞–∑–æ–≤–∞–Ω–∏—è –≤–∏–¥–∞  $ùëéùë•+ùëè$  —Ç–∞–∫, —á—Ç–æ –ø–æ—Å–ª–µ –Ω–æ—Ä–º–∞–ª–∏–∑–∞—Ü–∏–∏ –º–∞–∫—Å–∏–º–∞–ª—å–Ω—ã–π —ç–ª–µ–º–µ–Ω—Ç –º–∞—Åc–∏–≤–∞ –±—É–¥–µ—Ç —Ä–∞–≤–µ–Ω 1.0, –º–∏–Ω–∏–º–∞–ª—å–Ω—ã–π 0.0

In [65]:
import numpy as np
arr = np.random.random(size=(4, 7))
arr -= np.amin(arr)
arr /= np.amax(arr)
print(arr)

[[0.53112952 0.12660014 0.63373329 0.96249223 0.37326664 0.32503035
  0.76746301]
 [0.18249353 0.8829056  0.48667806 0.43074707 0.83784403 0.18021203
  0.10158437]
 [0.63352767 0.         0.5103141  0.13117993 0.33891258 0.35954023
  0.31734566]
 [0.71608685 0.87832236 0.22644207 1.         0.25540312 0.71633065
  0.0298658 ]]


2. –°–æ–∑–¥–∞—Ç—å –º–∞—Ç—Ä–∏—Ü—É 8 –Ω–∞ 10 –∏–∑ —Å–ª—É—á–∞–π–Ω—ã—Ö —Ü–µ–ª—ã—Ö (–∏—Å–ø–æ–ª—å–∑—É—è –º–æ–¥—É–ª—å `numpy.random`) —á–∏—Å–µ–ª –∏–∑ –¥–∏–∞–ø–æ–∑–æ–Ω–∞ –æ—Ç 0 –¥–æ 10 –∏ –Ω–∞–π—Ç–∏ –≤ –Ω–µ–π —Å—Ç—Ä–æ–∫—É (–µ–µ –∏–Ω–¥–µ–∫—Å –∏ –≤—ã–≤–µ—Å—Ç–∏ —Å–∞–º—É —Å—Ç—Ä–æ–∫—É), –≤ –∫–æ—Ç–æ—Ä–æ–π —Å—É–º–º–∞ –∑–Ω–∞—á–µ–Ω–∏–π –º–∏–Ω–∏–º–∞–ª—å–Ω–∞.

In [66]:
arr = np.random.randint(0, 11, (8, 10))
ind = arr.sum(axis=1).argmin()
print(f"–°—Ç—Ä–æ–∫–∞ {arr[ind]}, –ò–Ω–¥–µ–∫—Å {ind}")

–°—Ç—Ä–æ–∫–∞ [ 3  0 10  1  4  5  0  3  0  4], –ò–Ω–¥–µ–∫—Å 7


3. –ù–∞–π—Ç–∏ –µ–≤–∫–ª–∏–¥–æ–≤–æ —Ä–∞—Å—Å—Ç–æ—è–Ω–∏–µ –º–µ–∂–¥—É –¥–≤—É–º—è –æ–¥–Ω–æ–º–µ—Ä–Ω—ã–º–∏ –≤–µ–∫—Ç–æ—Ä–∞–º–∏ –æ–¥–∏–Ω–∞–∫–æ–≤–æ–π —Ä–∞–∑–º–µ—Ä–Ω–æ—Å—Ç–∏.

In [67]:
arr1 = np.random.randint(0, 11, (1, 5))
arr2 = np.random.randint(0, 11, (1, 5))
print(np.sum((arr1 - arr2) ** 2))

135


4. –†–µ—à–∏—Ç—å –º–∞—Ç—Ä–∏—á–Ω–æ–µ —É—Ä–∞–≤–Ω–µ–Ω–∏–µ `A*X*B=-C` - –Ω–∞–π—Ç–∏ –º–∞—Ç—Ä–∏—Ü—É `X`. –ì–¥–µ `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [68]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
c *= -1
a = np.linalg.inv(a)
b = np.linalg.inv(b)
x = a @ c @ b
print(x)


[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## –õ–∞–±–æ—Ä–∞—Ç–æ—Ä–Ω–∞—è —Ä–∞–±–æ—Ç–∞ ‚Ññ1

–ó–∞–º–µ—á–∞–Ω–∏–µ: –ø—Ä–∏ —Ä–µ—à–µ–Ω–∏–∏ –¥–∞–Ω–Ω—ã—Ö –∑–∞–¥–∞—á –Ω–µ –ø–æ–¥—Ä–∞–∑—É–º–µ–≤–∞–µ—Ç—Å—è –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ü–∏–∫–ª–æ–≤ –∏–ª–∏ –≥–µ–Ω–µ—Ä–∞—Ç–æ—Ä–æ–≤ Python, –µ—Å–ª–∏ –≤ –∑–∞–¥–∞–Ω–∏–∏ –Ω–µ —Å–∫–∞–∑–∞–Ω–æ –æ–±—Ä–∞—Ç–Ω–æ–≥–æ. –†–µ—à–µ–Ω–∏–µ –¥–æ–ª–∂–Ω–æ –æ–ø–∏—Ä–∞—Ç—å—Å—è –Ω–∞ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è —Ñ—É–Ω–∫—Ü–∏–æ–Ω–∞–ª–∞ –±–∏–±–ª–∏–æ—Ç–µ–∫–∏ `numpy`.

1. –§–∞–π–ª `minutes_n_ingredients.csv` —Å–æ–¥–µ—Ä–∂–∏—Ç –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ–± –∏–¥–µ–Ω—Ç–∏—Ñ–∏–∫–∞—Ç–æ—Ä–µ —Ä–µ—Ü–µ–ø—Ç–∞, –≤—Ä–µ–º–µ–Ω–∏ –µ–≥–æ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –≤ –º–∏–Ω—É—Ç–∞—Ö –∏ –∫–æ–ª–∏—á–µ—Å—Ç–≤–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã—Ö –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤. –°—á–∏—Ç–∞–π—Ç–µ –¥–∞–Ω–Ω—ã–µ –∏–∑ —ç—Ç–æ–≥–æ —Ñ–∞–π–ª–∞ –≤ –≤–∏–¥–µ –º–∞—Å—Å–∏–≤–∞ `numpy` —Ç–∏–ø–∞ `int32`, –∏—Å–ø–æ–ª—å–∑—É—è `np.loadtxt`. –í—ã–≤–µ–¥–∏—Ç–µ –Ω–∞ —ç–∫—Ä–∞–Ω –ø–µ—Ä–≤—ã–µ 5 —Å—Ç—Ä–æ–∫ –º–∞—Å—Å–∏–≤–∞.

In [69]:
arr = np.loadtxt("minutes_n_ingredients.csv", dtype="int32", delimiter=",", skiprows=1)
print(arr[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∑–Ω–∞—á–µ–Ω–∏–µ, –º–∏–Ω–∏–º—É–º, –º–∞–∫—Å–∏–º—É–º –∏ –º–µ–¥–∏–∞–Ω—É –ø–æ –∫–∞–∂–¥–æ–º—É –∏–∑ —Å—Ç–æ–ª–±—Ü–æ–≤, –∫—Ä–æ–º–µ –ø–µ—Ä–≤–æ–≥–æ.

In [70]:
print(f"Min {np.amin(arr, axis=0)[1:]}\nMax {np.max(arr, axis=0)[1:]}\nMed {np.median(arr, axis=0)[1:]}")

Min [0 1]
Max [2147483647         39]
Med [40.  9.]


3. –û–≥—Ä–∞–Ω–∏—á—å—Ç–µ —Å–≤–µ—Ä—Ö—É –∑–Ω–∞—á–µ–Ω–∏—è –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç–∏ –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è —Ä–µ—Ü–µ–ø—Ç–∞ –∑–Ω–∞—á–µ–Ω–∏–µ–º –∫–≤–∞–Ω—Ç–∏–ª—è $q_{0.75}$. 

In [71]:
q = np.quantile(arr, 0.75, axis=0)
arr[arr[:, 1] > q[1]] = q[1]

4. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, –¥–ª—è —Å–∫–æ–ª—å–∫–∏—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ —É–∫–∞–∑–∞–Ω–∞ –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å, —Ä–∞–≤–Ω–∞—è –Ω—É–ª—é. –ó–∞–º–µ–Ω–∏—Ç–µ –¥–ª—è —Ç–∞–∫–∏—Ö —Å—Ç—Ä–æ–∫ –∑–Ω–∞—á–µ–Ω–∏–µ –≤ –¥–∞–Ω–Ω–æ–º —Å—Ç–æ–ª–±—Ü–µ –Ω–∞ 1.

In [72]:
print(np.sum(arr[:, 1] == 0))
arr[arr[:, 1] == 0] = 1

479


5. –ü–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–æ–≤ –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ.

In [73]:
print(len(np.unique(arr[:, 0])))

74984


6. –°–∫–æ–ª—å–∫–æ –∏ –∫–∞–∫–∏—Ö —Ä–∞–∑–ª–∏—á–Ω—ã—Ö –∑–Ω–∞—á–µ–Ω–∏–π –∫–æ–ª-–≤–∞ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Å—É—Ç–≤—É–µ—Ç –≤ —Ä–µ—Ü–µ–ø—Ç–∞—Ö –∏–∑ –¥–∞—Ç–∞—Å–µ—Ç–∞?

In [74]:
print(np.unique(arr[:, 2]), len(np.unique(arr[:, 2])))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 33 34 65] 33


7. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –º–∞—Å—Å–∏–≤–∞, —Å–æ–¥–µ—Ä–∂–∞—â—É—é –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é —Ç–æ–ª—å–∫–æ –æ —Ä–µ—Ü–µ–ø—Ç–∞—Ö, —Å–æ—Å—Ç–æ—è—â–∏—Ö –Ω–µ –±–æ–ª–µ–µ —á–µ–º –∏–∑ 5 –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤.

In [75]:
print(arr[arr[:, 2] <= 5, :])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. –î–ª—è –∫–∞–∂–¥–æ–≥–æ —Ä–µ—Ü–µ–ø—Ç–∞ –ø–æ—Å—á–∏—Ç–∞–π—Ç–µ, —Å–∫–æ–ª—å–∫–æ –≤ —Å—Ä–µ–¥–Ω–µ–º –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –ø—Ä–∏—Ö–æ–¥–∏—Ç—Å—è –Ω–∞ –æ–¥–Ω—É –º–∏–Ω—É—Ç—É —Ä–µ—Ü–µ–ø—Ç–∞. –ù–∞–π–¥–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∑–Ω–∞—á–µ–Ω–∏–µ —ç—Ç–æ–π –≤–µ–ª–∏—á–∏–Ω—ã –¥–ª—è –≤—Å–µ–≥–æ –¥–∞—Ç–∞—Å–µ—Ç–∞

In [76]:
ing_m = np.array(np.divide(arr[:, 2], arr[:, 1]))
print(ing_m, np.max(ing_m))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        1.        ] 23.0


9. –í—ã—á–∏—Å–ª–∏—Ç–µ —Å—Ä–µ–¥–Ω–µ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –¥–ª—è —Ç–æ–ø-100 —Ä–µ—Ü–µ–ø—Ç–æ–≤ —Å –Ω–∞–∏–±–æ–ª—å—à–µ–π –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å—é

In [77]:
sor = arr[arr[:, 1].argsort()][::-1]
print(np.mean(sor[:100, 2]))

61.12


10. –í—ã–±–µ—Ä–∏—Ç–µ —Å–ª—É—á–∞–π–Ω—ã–º –æ–±—Ä–∞–∑–æ–º –∏ –≤—ã–≤–µ–¥–∏—Ç–µ –∏–Ω—Ñ–æ—Ä–º–∞—Ü–∏—é –æ 10 —Ä–∞–∑–ª–∏—á–Ω—ã—Ö —Ä–µ—Ü–µ–ø—Ç–∞—Ö

In [78]:
idx = np.random.randint(100000, size=10)
print(arr[idx, :])

[[    65     65     65]
 [    65     65     65]
 [106289     64      5]
 [ 69986     55     11]
 [437549     25      9]
 [218817     45      5]
 [    65     65     65]
 [154393     45     10]
 [466376     60      8]
 [265562     40     12]]


11. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç —Ä–µ—Ü–µ–ø—Ç–æ–≤, –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä—ã—Ö –º–µ–Ω—å—à–µ —Å—Ä–µ–¥–Ω–µ–≥–æ.

In [79]:
sr = np.mean(arr[:, 2])
print(f"{len(arr[arr[:, 2] < sr]) / len(arr) * 100}%")

75.345%


12. –ù–∞–∑–æ–≤–µ–º "–ø—Ä–æ—Å—Ç—ã–º" —Ç–∞–∫–æ–π —Ä–µ—Ü–µ–ø—Ç, –¥–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å –≤—ã–ø–æ–ª–Ω–µ–Ω–∏—è –∫–æ—Ç–æ—Ä–æ–≥–æ –Ω–µ –±–æ–ª—å—à–µ 20 –º–∏–Ω—É—Ç –∏ –∫–æ–ª-–≤–æ –∏–Ω–≥—Ä–µ–¥–∏–µ–Ω—Ç–æ–≤ –≤ –∫–æ—Ç–æ—Ä–æ–º –Ω–µ –±–æ–ª—å—à–µ 5. –°–æ–∑–¥–∞–π—Ç–µ –≤–µ—Ä—Å–∏—é –¥–∞—Ç–∞—Å–µ—Ç–∞ —Å –¥–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω—ã–º —Å—Ç–æ–ª–±—Ü–æ–º, –∑–Ω–∞—á–µ–Ω–∏—è–º–∏ –∫–æ—Ç–æ—Ä–æ–≥–æ —è–≤–ª—è—é—Ç—Å—è 1, –µ—Å–ª–∏ —Ä–µ—Ü–µ–ø—Ç –ø—Ä–æ—Å—Ç–æ–π, –∏ 0 –≤ –ø—Ä–æ—Ç–∏–≤–Ω–æ–º —Å–ª—É—á–∞–µ.

In [80]:
new = arr.copy()
new = np.append(new, np.logical_and(new[:, 1] <= 20, new[:, 2] <= 5).astype(int)[:, None], axis=1)
print(new)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [    65     65     65      0]]


13. –í—ã–≤–µ–¥–∏—Ç–µ –ø—Ä–æ—Ü–µ–Ω—Ç "–ø—Ä–æ—Å—Ç—ã—Ö" —Ä–µ—Ü–µ–ø—Ç–æ–≤ –≤ –¥–∞—Ç–∞—Å–µ—Ç–µ

In [81]:
print(f"{np.sum(new[:, -1]) / 1000}%")

9.943%


14. –†–∞–∑–¥–µ–ª–∏–º —Ä–µ—Ü–µ–ø—Ç—ã –Ω–∞ –≥—Ä—É–ø–ø—ã –ø–æ —Å–ª–µ–¥—É—é—â–µ–º—É –ø—Ä–∞–≤–∏–ª—É. –ù–∞–∑–æ–≤–µ–º —Ä–µ—Ü–µ–ø—Ç—ã –∫–æ—Ä–æ—Ç–∫–∏–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –º–µ–Ω–µ–µ 10 –º–∏–Ω—É—Ç; —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –±–æ–ª–µ–µ 10, –Ω–æ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç; –∏ –¥–ª–∏–Ω–Ω—ã–º–∏, –µ—Å–ª–∏ –∏—Ö –ø—Ä–æ–¥–æ–ª–∂–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å —Å–æ—Å—Ç–∞–≤–ª—è–µ—Ç –Ω–µ –º–µ–Ω–µ–µ 20 –º–∏–Ω—É—Ç. –°–æ–∑–¥–∞–π—Ç–µ —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤, –≥–¥–µ –Ω—É–ª–µ–≤–∞—è –æ—Å—å –æ—Ç–≤–µ—á–∞–µ—Ç –∑–∞ –Ω–æ–º–µ—Ä –≥—Ä—É–ø–ø—ã (–∫–æ—Ä–æ—Ç–∫–∏–π, —Å—Ç–∞–Ω–¥–∞—Ä—Ç–Ω—ã–π –∏–ª–∏ –¥–ª–∏–Ω–Ω—ã–π —Ä–µ—Ü–µ–ø—Ç), –ø–µ—Ä–≤–∞—è –æ—Å—å - –∑–∞ —Å–∞–º —Ä–µ—Ü–µ–ø—Ç –∏ –≤—Ç–æ—Ä–∞—è –æ—Å—å - –∑–∞ —Ö–∞—Ä–∞–∫—Ç–µ—Ä–∏—Å—Ç–∏–∫–∏ —Ä–µ—Ü–µ–ø—Ç–∞. –í—ã–±–µ—Ä–∏—Ç–µ –º–∞–∫—Å–∏–º–∞–ª—å–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ —Ä–µ—Ü–µ–ø—Ç–æ–≤ –∏–∑ –∫–∞–∂–¥–æ–π –≥—Ä—É–ø–ø—ã —Ç–∞–∫–∏–º –æ–±—Ä–∞–∑–æ–º, —á—Ç–æ–±—ã –±—ã–ª–æ –≤–æ–∑–º–æ–∂–Ω–æ —Å—Ñ–æ—Ä–º–∏—Ä–æ–≤–∞—Ç—å —Ç—Ä–µ—Ö–º–µ—Ä–Ω—ã–π –º–∞—Å—Å–∏–≤. –í—ã–≤–µ–¥–∏—Ç–µ —Ñ–æ—Ä–º—É –ø–æ–ª—É—á–µ–Ω–Ω–æ–≥–æ –º–∞—Å—Å–∏–≤–∞.

In [82]:
sm = arr[arr[:, 1] < 10]
st = arr[np.logical_and(10 <= arr[:, 1], arr[:, 1] < 20)]
bi = arr[20 <= arr[:, 1]]
mn_shape = min(sm.shape[0], st.shape[0], bi.shape[0])
sm = sm[:mn_shape, :]
st = st[:mn_shape, :]
bi = bi[:mn_shape, :]
res_arr = np.array([sm, st, bi])
print(res_arr)

[[[ 67660      5      6]
  [366174      7      9]
  [204134      5      3]
  ...
  [420725      5      3]
  [     1      1      1]
  [370915      5      4]]

 [[ 94746     10      6]
  [ 33941     18      9]
  [446597     15      5]
  ...
  [  9831     15      7]
  [335859     12     14]
  [256812     10      3]]

 [[127244     60     16]
  [ 23891     25      7]
  [157911     60     14]
  ...
  [168901     25      7]
  [392339     35     13]
  [206732     45     10]]]
